---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: VMware vSphere용 ONTAP 툴을 구축하기 전에 배포 패키지의 공간 요구 사항과 몇 가지 기본적인 호스트 시스템 요구 사항을 숙지해야 합니다. 
---
= VMware vSphere 구축을 위한 ONTAP 툴 사전 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴을 구축하기 전에 배포 패키지의 공간 요구 사항과 몇 가지 기본적인 호스트 시스템 요구 사항을 숙지해야 합니다.

VMware vSphere용 ONTAP 툴을 VMware vCSA(vCenter Server 가상 어플라이언스)와 함께 사용할 수 있습니다. VMware vSphere용 ONTAP 툴을 ESXi 시스템이 포함된 지원되는 vSphere 클라이언트에 구축해야 합니다.



== 시스템 요구 사항

* * 노드별 설치 패키지 공간 요구 사항 *
+
** 씬 프로비저닝된 설치의 경우 10GB
** 일반 프로비저닝 설치의 경우 248GB


* * 노드당 호스트 시스템 크기 조정 요구 사항 * 배포 크기 및 노드당 권장 메모리는 아래 표와 같습니다.


|===


| * 배포 유형 * | * CPU * | * 메모리(GB) * 


| 소형(S) | 8 | 16 


| 중간(M) | 12 | 24 


| 크게(L) | 16 | 32 
|===
자세한 내용은 아래 _VMware vSphere용 ONTAP 툴을 구축하는 데 필요한 구성 제한_섹션을 참조하십시오.



== 최소 스토리지 및 애플리케이션 요구사항

|===
| 스토리지, 호스트 및 애플리케이션 | 최소 버전 요구 사항 


| ONTAP | ONTAP 9.12.1, 9.13.1, 9.14.1 및 9.15.1의 최신 패치 릴리스. 


| ESXi 호스트 | ESXi 7.0.3을 참조하십시오 


| vCenter Server입니다 | vCenter 7.0U3 


| VASA 공급자 | 3.0 


| OVA 응용 프로그램 | 10.2 
|===
상호 운용성 매트릭스 툴(IMT)에는 지원되는 ONTAP 버전, vCenter Server, ESXi 호스트 및 플러그인 애플리케이션에 대한 최신 정보가 포함되어 있습니다.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["상호 운용성 매트릭스 툴"^]



== VMware vSphere용 ONTAP 툴을 구축하기 위한 구성 제한

다음 표를 참조하여 VMware vSphere용 ONTAP 툴을 구성할 수 있습니다.

|===


| * 배포 * | * 유형 * | * VVol 수 * | * 호스트 수 * | * 프로토콜 유형 * 


| 손쉬운 배포 | 소형(S) | 12K 이하 | 32 | NFS, iSCSI를 지원합니다 


| 손쉬운 배포 | 중간(M) | 24K 이하 | 64 | NFS, iSCSI를 지원합니다 


| 고가용성 | 소형(S) | 24K 이하 | 64 | NFS, iSCSI를 지원합니다 


| 고가용성 | 중간(M) | 5만 | 128 | NFS, iSCSI를 지원합니다 


| 고가용성 | 크게(L) | 100k 이하 | 256 [참고] 표에 있는 호스트 수는 여러 vCenter의 총 호스트 수를 보여 줍니다. | NFS, iSCSI를 지원합니다 
|===
노드당 호스트 시스템 크기 조정 요구 사항에 대한 자세한 내용은 을 link:../deploy/prerequisites.html["VMware vSphere용 ONTAP 툴을 구축하기 위한 사전 요구 사항"]참조하십시오.



== VMware vSphere용 ONTAP 툴 - SRA(Storage Replication Adapter)

다음 표에는 VMware vSphere용 ONTAP 툴을 사용하여 VMware 라이브 사이트 복구 인스턴스당 지원되는 수가 나와 있습니다.

|===
| * vCenter 배포 크기 * | * 소형 * | * 중간 * 


| 스토리지 기반 복제를 사용하여 보호를 위해 구성된 총 가상 시스템 수입니다 | 2000 | 5000 


| 스토리지 기반 복제 보호 그룹의 총 수입니다 | 250 | 250 


| 복구 계획당 총 보호 그룹 수입니다 | 50 | 50 


| 복제된 데이터 저장소 수입니다 | 255 | 255 


| VM 수입니다 | 4000 | 7000 
|===
다음 표에는 VMware Live Site Recovery의 수와 VMware vSphere 구축 크기용 ONTAP 툴의 수가 나와 있습니다.

|===


| * VMware Live Site Recovery 인스턴스 수 * | * ONTAP 도구 배포 크기 * 


| 최대 4개 | 작은 크기 


| 4 - 8 | 중간 


| 8개 이상 | 대형 
|===
자세한 내용은 을 https://docs.vmware.com/en/VMware-Live-Recovery/services/vmware-live-site-recovery/GUID-3AD7D565-8A27-450C-8493-7B53F995BB14.html["VMware Live Site Recovery의 운영상의 한계"]참조하십시오.



== 배포 전 검사

배포를 진행하기 전에 다음 항목이 준비되어 있는지 확인합니다.

* vCenter Server 환경이 설정 및 구성됩니다.
* (선택 사항) 자동화 사용자의 경우 - NetApp에서 제공한 Postman 컬렉션 JSON 파일이 수집됩니다.
* OVA를 구축하기 위한 상위 vCenter Server 자격 증명이 마련되어 있습니다.
+

NOTE: 상위 vCenter Server 암호에는 이러한 특수 문자($,',")가 포함될 수 없습니다.

* VMware vSphere용 ONTAP 툴이 구축 후 에 연결하여 등록할 vCenter Server 인스턴스에 대한 로그인 자격 증명이 있습니다.
* 브라우저 캐시가 삭제됩니다.
* 비 HA 배포에 사용할 수 있는 3개의 무료 IP 주소, 로드 밸런서용 무료 IP 주소 1개, Kubernetes 컨트롤 플레인용 무료 IP 주소 1개, 노드에 대한 IP 주소 1개가 있어야 합니다. HA 배포의 경우 이 세 개의 IP 주소와 함께 두 번째 및 세 번째 노드에 대해 두 개의 추가 IP 주소가 필요합니다. HA 및 비 HA 배포를 모두 할당하기 전에 호스트 이름을 DNS의 사용 가능한 IP 주소에 매핑해야 합니다. HA 배포의 5개 IP 주소와 비 HA 배포의 3개 IP 주소는 모두 배포를 위해 선택된 동일한 VLAN에 있어야 합니다.


* 사용자 지정 CA 인증서가 필수인 다중 vCenter 배포의 경우 인증서가 발급된 도메인 이름이 가상 IP 주소에 매핑되어 있는지 확인합니다. 도메인 이름에 _nslookup_check 를 수행하여 도메인이 의도된 IP 주소로 확인되는지 확인합니다. 인증서는 부하 분산 장치 IP 주소의 도메인 이름과 IP 주소를 사용하여 만들어야 합니다.
* HA가 아닌 고급 및 HA 구성에서 VMware vSphere 10.2용 ONTAP 툴을 설치하기 전에 KB 문서: https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/pre-requisites_for_installing_OTV_10.1_and_10.2_in_NonHA_Advanced_and_HA["비 HA 고급 및 HA 구성을 위한 사전 요구 사항"]

