---
permalink: protect/configure-storage-replication-adapter-for-highly-scaled-environment.html 
sidebar: sidebar 
keywords:  
summary: 'SRA\(Storage Replication Adapter\)의 권장 설정에 따라 스토리지 시간 초과 간격을 구성하여 확장성이 높은 환경에서 최적으로 수행되도록 해야 합니다.' 
---
= 확장성이 높은 환경에 맞게 SRA를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
확장성이 높은 환경에서 최적으로 수행되도록 SRA(Storage Replication Adapter)의 권장 설정에 따라 스토리지 시간 초과 간격을 구성해야 합니다.



== 저장소 공급자 설정

확장 환경에 대해 VMware Live Site Recovery에서 다음 시간 초과 값을 설정해야 합니다.

|===


| * 고급 설정 * | * 시간 초과 값 * 


 a| 
`StorageProvider.resignatureTimeout`
 a| 
설정 값을 900초에서 12000초로 늘립니다.



 a| 
`storageProvider.hostRescanDelaySec`
 a| 
60



 a| 
`storageProvider.hostRescanRepeatCnt`
 a| 
20



 a| 
`storageProvider.hostRescanTimeoutSec`
 a| 
높은 값을 설정합니다(예: 99999).

|===
 `StorageProvider.autoResignatureMode`옵션을 활성화해야 합니다.

Storage Provider 설정을 수정하는 방법에 대한 자세한 내용은 VMware 설명서를 참조하십시오.

https://docs.vmware.com/en/VMware-Live-Site-Recovery/9.0/vmware-live-site-recovery/GUID-E4060824-E3C2-4869-BC39-76E88E2FF9A0.html["VMware vSphere 설명서: 스토리지 공급자 설정 변경"]



== 저장소 설정

시간 초과에 도달하면 `storage.commandTimeout` 및 의 값을 `storage.maxConcurrentCommandCnt` 더 높은 값으로 늘립니다.


NOTE: 지정된 시간 제한 간격이 최대값입니다. 최대 시간 초과에 도달할 때까지 기다릴 필요가 없습니다. 대부분의 명령이 설정된 최대 시간 제한 간격 내에 완료됩니다.

자세한 내용은 SAN Provider 설정 수정에 대한 VMware 설명서를 참조하십시오.

https://docs.vmware.com/en/VMware-Live-Site-Recovery/9.0/vmware-live-site-recovery/GUID-711FD223-50DB-414C-A2A7-3BEB8FAFDBD9.html["VMware Site Recovery Manager 설명서: 스토리지 설정 변경"]
