---
permalink: concepts/ontap-roles.html 
sidebar: sidebar 
keywords:  
summary: 'VMware vSphere용 ONTAP 툴 및 역할 기반 액세스 제어\(RBAC\)로 작업할 때 권장되는 몇 가지 ONTAP 역할을 설정할 수 있습니다. 이러한 역할에는 VMware vSphere 작업을 위해 ONTAP 툴을 통해 실행되는 필수 스토리지 작업을 수행하는 데 필요한 ONTAP 권한이 포함됩니다.' 
---
= VMware vSphere용 ONTAP 툴에 대해 권장되는 ONTAP 역할
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 및 역할 기반 액세스 제어(RBAC)에 대한 ONTAP 툴로 작업하기 위해 권장되는 여러 ONTAP 역할을 설정할 수 있습니다. 이러한 역할에는 VMware vSphere 작업을 위해 ONTAP 툴에서 실행되는 스토리지 작업을 수행하는 데 필요한 ONTAP 권한이 포함됩니다.

새로운 사용자 역할을 생성하려면 ONTAP를 실행하는 스토리지 시스템의 관리자로 로그인해야 합니다. ONTAP 시스템 관리자 9.8P1 이상을 사용하여 ONTAP 역할을 생성할 수 있습니다.

각 ONTAP 역할에는 역할의 자격 증명을 구성하는 연결된 사용자 이름 및 암호 쌍이 있습니다. 이러한 자격 증명을 사용하여 로그인하지 않으면 해당 역할과 연결된 스토리지 작업에 액세스할 수 없습니다.

보안 조치로서 VMware vSphere 관련 ONTAP 역할에 대한 ONTAP 툴은 계층적으로 정렬됩니다. 즉, 첫 번째 역할이 가장 제한적이며 VMware vSphere 스토리지 작업을 위한 가장 기본적인 ONTAP 툴 세트와 관련된 권한만 가집니다. 다음 역할에는 자체 권한 및 이전 역할과 연결된 모든 권한이 포함됩니다. 각 추가 역할은 지원되는 스토리지 작업과 관련하여 덜 제한적입니다.

다음은 VMware vSphere용 ONTAP 툴을 사용할 때 권장되는 ONTAP RBAC 역할 중 일부입니다. 이러한 역할을 생성한 후 가상 시스템 프로비저닝과 같이 스토리지와 관련된 작업을 수행해야 하는 사용자에게 역할을 할당할 수 있습니다.

|===


| * 역할 * | * 권한 * 


| 탐색 | 이 역할을 통해 스토리지 시스템을 추가할 수 있습니다. 


| 스토리지 생성 | 이 역할을 사용하여 스토리지를 생성할 수 있습니다. 이 역할에는 검색 역할과 연결된 모든 권한도 포함됩니다. 


| 스토리지 수정 | 이 역할을 사용하여 스토리지를 수정할 수 있습니다. 이 역할에는 검색 역할 및 스토리지 생성 역할과 연결된 모든 권한도 포함됩니다. 


| 스토리지 폐기 | 이 역할을 사용하면 스토리지를 제거할 수 있습니다. 이 역할에는 검색 역할, 스토리지 생성 역할 및 스토리지 수정 역할과 연결된 모든 권한도 포함됩니다. 
|===
VMware vSphere용 ONTAP 툴을 사용하는 경우에는 PBM(정책 기반 관리) 역할도 설정해야 합니다. 이 역할을 통해 스토리지 정책을 사용하여 스토리지를 관리할 수 있습니다. 이 역할을 수행하려면 "Discovery" 역할도 설정해야 합니다.
