---
permalink: concepts/vcenter-server-role-based-access-control-features.html 
sidebar: sidebar 
keywords:  
summary: 'vCenter Server는 vSphere 객체에 대한 액세스를 제어할 수 있도록 역할 기반 액세스 제어(RBAC)를 제공합니다.' 
---
= VMware vSphere용 ONTAP 툴의 역할 기반 액세스 제어 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter Server는 vSphere 객체에 대한 액세스를 제어할 수 있는 RBAC(역할 기반 액세스 제어)를 제공합니다. vCenter Server는 역할 및 Privileges를 통해 사용자 및 그룹 권한을 사용하여 인벤토리의 다양한 수준에서 중앙 집중식 인증 및 인증 서비스를 제공합니다. vCenter Server는 RBAC 관리를 위한 5가지 주요 구성 요소:

|===


| 구성 요소 | 설명 


| 권한 | 권한은 vSphere에서 작업을 수행하기 위한 액세스를 설정하거나 거부합니다. 


| 역할 | 역할에는 하나 이상의 시스템 권한이 포함되며, 여기서 각 권한은 시스템의 특정 개체 또는 개체 유형에 대한 관리 권한을 정의합니다. 사용자에게 역할을 할당하면 사용자는 해당 역할에 정의된 권한의 기능을 상속합니다. 


| 사용자 및 그룹 | 사용자와 그룹은 AD(Active Directory)에서 역할을 할당할 수 있는 권한에 사용됩니다. vCenter Server에는 사용할 수 있는 고유한 로컬 사용자 및 그룹이 있습니다. 


| 권한 | 사용 권한을 사용하면 Privileges를 사용자 또는 그룹에 할당하여 vCenter Server 내의 개체를 변경할 수 있습니다. vCenter Server 사용 권한은 ESXi 호스트에 직접 로그인하는 사용자가 아니라 vCenter Server에 로그인하는 사용자에게만 영향을 줍니다. 


| 오브젝트 | 작업이 수행되는 엔티티입니다. VMware vCenter 객체는 데이터 센터, 폴더, 리소스 풀, 클러스터, 호스트, 및 VM을 지원합니다 
|===
작업을 성공적으로 완료하려면 적절한 vCenter Server RBAC 역할이 있어야 합니다. 작업 중에 VMware vSphere용 ONTAP 툴은 사용자의 ONTAP 권한을 확인하기 전에 사용자의 vCenter Server 역할을 확인합니다.


NOTE: vCenter Server 역할은 VMware vSphere vCenter 사용자용 ONTAP 툴에 적용되며 관리자에게는 적용되지 않습니다. 기본적으로 관리자는 제품에 대한 모든 액세스 권한을 가지며 할당된 역할이 필요하지 않습니다.

사용자 및 그룹은 vCenter Server 역할의 일부가 되어 역할에 액세스할 수 있습니다.



== vCenter Server에 대한 역할 할당 및 수정에 대한 주요 사항

vSphere 객체 및 작업에 대한 액세스를 제한하려는 경우에만 vCenter Server 역할을 설정해야 합니다. 그렇지 않으면 관리자로 로그인할 수 있습니다. 이 로그인을 통해 모든 vSphere 객체에 자동으로 액세스할 수 있습니다.

역할을 할당하는 위치에 따라 사용자가 수행할 수 있는 VMware vSphere 작업에 대한 ONTAP 툴이 결정됩니다. 언제든지 하나의 역할을 수정할 수 있습니다. 역할 내의 권한을 변경하는 경우 해당 역할과 연결된 사용자는 로그아웃한 다음 다시 로그인하여 업데이트된 역할을 사용하도록 설정해야 합니다.



== VMware vSphere용 ONTAP 툴과 함께 패키지로 제공되는 표준 역할입니다

vCenter Server 권한 및 RBAC를 간편하게 사용할 수 있도록 VMware vSphere용 ONTAP 툴은 VMware vSphere 역할에 사용할 수 있는 표준 ONTAP 툴을 제공합니다. 이 툴을 사용하면 VMware vSphere 작업에 대한 주요 ONTAP 툴을 수행할 수 있습니다. 또한 정보를 볼 수는 있지만 작업을 수행할 수 없는 읽기 전용 역할도 있습니다.

vSphere Client 홈 페이지에서 * 역할 * 을 클릭하여 VMware vSphere 표준 역할용 ONTAP 툴을 볼 수 있습니다. VMware vSphere용 ONTAP 툴이 제공하는 역할을 사용하면 다음 작업을 수행할 수 있습니다.

|===


| * 역할 * | * 설명 * 


| VMware vSphere 관리자용 NetApp ONTAP 툴 | VMware vSphere 작업을 위한 일부 ONTAP 툴을 수행하는 데 필요한 모든 기본 vCenter Server 권한 및 ONTAP 툴별 권한을 제공합니다. 


| VMware vSphere 읽기 전용용 NetApp ONTAP 툴 | ONTAP 도구에 대한 읽기 전용 액세스를 제공합니다. 이러한 사용자는 액세스가 제어되는 VMware vSphere 작업에 대한 ONTAP 툴을 수행할 수 없습니다. 


| VMware vSphere 프로비저닝용 NetApp ONTAP 툴  a| 
에는 스토리지 용량 할당에 필요한 몇 가지 기본 vCenter Server 권한 및 ONTAP 툴별 권한이 나와 있습니다. 다음 작업을 수행할 수 있습니다.

* 새 데이터 저장소를 생성합니다
* 데이터 저장소를 관리합니다


|===
ONTAP tools Manager 관리자 역할이 vCenter Server에 등록되지 않았습니다. 이 역할은 ONTAP 도구 관리자에 따라 다릅니다.

회사에서 VMware vSphere 역할에 대한 표준 ONTAP 툴보다 더 엄격한 역할을 구현해야 하는 경우 VMware vSphere 역할용 ONTAP 툴을 사용하여 새로운 역할을 생성할 수 있습니다.

이 경우 VMware vSphere 역할에 필요한 ONTAP 툴을 클론 생성한 다음 사용자가 필요로 하는 권한만 갖도록 클론 생성된 역할을 편집합니다.



== ONTAP 스토리지 백 엔드 및 vSphere 객체에 대한 권한

vCenter Server 권한이 충분하면 VMware vSphere용 ONTAP 툴이 스토리지 백엔드 자격 증명(사용자 이름 및 암호)과 연결된 ONTAP RBAC 권한(ONTAP 역할)을 확인합니다. 해당 스토리지 백엔드에서 VMware vSphere용 ONTAP 툴에 필요한 스토리지 작업을 수행할 수 있는 권한이 있는지 여부를 확인합니다. 올바른 ONTAP Privileges가 있는 경우 스토리지 백엔드에 액세스하고 VMware vSphere 작업에 대한 ONTAP 툴을 수행할 수 있습니다. ONTAP 역할에 따라 스토리지 백엔드에서 수행할 수 있는 VMware vSphere 작업에 대한 ONTAP 툴이 결정됩니다.
