---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: 'vCenter Server 인스턴스는 호스트, VM(가상 머신) 및 스토리지 백엔드를 제어할 수 있는 중앙 관리 플랫폼입니다.' 
---
= vCenter Server 인스턴스를 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter Server는 호스트, VM(가상 머신) 및 스토리지 백엔드를 제어할 수 있는 중앙 관리 플랫폼을 제공합니다.

* 이 작업에 대한 정보 *

VMware vSphere용 ONTAP 툴 인스턴스 하나를 사용하여 여러 vCenter Server 인스턴스를 추가하고 관리할 수 있습니다.

* 단계 *

. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://loadBalanceIP:8443/virtualization/ui/`
. 구축 중에 제공한 VMware vSphere 관리자 자격 증명용 ONTAP 툴을 사용하여 로그인합니다.
. 사이드바에서 * vCenters * 를 선택합니다.
. 온보드 vCenter Server 인스턴스에 * 추가 * 를 선택하고 vCenter IP 주소/호스트 이름, 사용자 이름, 암호 및 포트 세부 정보를 제공합니다.


vCenter Server 인스턴스를 ONTAP 툴에 추가하면 다음 작업이 자동으로 수행됩니다.

* vCenter Client 플러그인이 등록되었습니다
* 플러그인 및 API에 대한 사용자 지정 권한이 vCenter Server 인스턴스로 푸시됩니다
* 사용자 지정 역할이 생성되어 사용자를 관리합니다.


vCenter Server 인스턴스를 추가하면 VMware vSphere 플러그인용 ONTAP 툴이 자동으로 vCenter Server에 원격 플러그인으로 등록되며 vSphere 사용자 인터페이스 바로 가기에 플러그인이 표시됩니다.

플러그인은 vCenter Server 인스턴스에 _com.netapp.otv_ 키로 등록되며 vCenter Server 인스턴스의 ExtensionManager에서 볼 수 있습니다.
