---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 'VMware vSphere용 ONTAP 툴을 사용하여 VAAI\(NetApp NFS Plug-in for VMware vStorage APIs for Array Integration)를 설치할 수 있습니다.' 
---
= NFS VAAI 플러그인을 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴을 사용하여 VAAI(vSphere API for Array Integration)용 NetApp NFS 플러그인을 설치할 수 있습니다.

* 필요한 것 *

* VAAI용 NFS 플러그인용 설치 패키지를 (`.vib`NetApp 지원 사이트에서 다운로드해야 합니다. https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["VMware VAAI용 NetApp NFS 플러그인"]
* ESXi 호스트 7.0U3 최신 패치를 최소 버전 및 ONTAP 9.12.1Px(최신 P 릴리스) 9.13.1Px, 9.14.1Px 이상 버전으로 설치해야 합니다.
* ESXi 호스트의 전원을 켜고 NFS 데이터 저장소를 마운트해야 합니다.
*  `DataMover.HardwareAcceleratedMove` `DataMover.HardwareAcceleratedInit`, 및 `VMFS3.HardwareAcceleratedLocking` 호스트 설정의 값을 "`1""로 설정해야 합니다.
+
이러한 값은 권장 설정 대화 상자가 업데이트될 때 ESXi 호스트에서 자동으로 설정됩니다.

*  `vserver nfs modify -vserver vserver_name -vstorage enabled`명령을 사용하여 SVM(스토리지 가상 머신)에서 vStorage 옵션을 사용하도록 설정해야 합니다.
* NetApp NFS VAAI 플러그인 2.0을 사용하는 경우 ESXi 7.0U3 이상이 있어야 합니다.
* vSphere 6.5가 더 이상 사용되지 않으므로 vSphere 7.0U3 최신 패치 릴리즈가 있어야 합니다.
* vSphere 8.x는 NetApp NFS VAAI 플러그인 2.0.1(빌드 16)에서 지원됩니다.


* 단계 *

. ONTAP Tools for VMware vSphere 홈 페이지에서 * Settings * 를 클릭합니다.
. NFS VAAI Tools * 탭을 클릭합니다.
. VAAI 플러그인이 vCenter Server에 업로드되면 * Existing version * 섹션에서 * Change * 를 선택합니다. VAAI 플러그인이 vCenter Server에 업로드되지 않은 경우 * 업로드 * 버튼을 선택합니다.
.  `.vib`파일을 찾아 선택하고 * 업로드 * 를 클릭하여 ONTAP 도구에 파일을 업로드합니다.
. ESXi 호스트에 설치 * 를 클릭하고 NFS VAAI 플러그인을 설치할 ESXi 호스트를 선택한 다음 * 설치 * 를 클릭합니다.
+
플러그인 설치에 적합한 ESXi 호스트만 표시됩니다. 화면의 지시에 따라 설치를 완료해야 합니다. vSphere Web Client의 Recent Tasks 섹션에서 설치 진행률을 모니터링할 수 있습니다.

. 설치가 완료된 후 ESXi 호스트를 수동으로 재부팅해야 합니다.
+
VMware 관리자가 ESXi 호스트를 재부팅하면 VMware vSphere용 ONTAP 툴이 NFS VAAI 플러그인을 자동으로 감지합니다. 플러그인을 활성화하기 위한 추가 단계를 수행할 필요가 없습니다.





=== VAAI 복사 오프로드에 대한 올바른 NFS 내보내기 정책을 구성합니다

NFS 환경에서 VAAI를 구성할 때는 다음 요구 사항을 고려하여 내보내기 정책 규칙을 구성해야 합니다.

* 해당 볼륨에서 NFSv4 호출을 허용해야 합니다.
* 루트 사용자는 루트로 유지되어야 하고 NFSv4는 모든 접합 상위 볼륨에서 허용되어야 합니다.
* VAAI 지원 옵션은 관련 NFS 서버에서 설정해야 합니다.


절차에 대한 자세한 내용은 https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["VAAI 복사 오프로드에 대한 올바른 NFS 내보내기 정책을 구성합니다"] KB 문서 를 참조하십시오.
