---
permalink: configure/registration-process.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 원격 플러그인 인터페이스용 ONTAP 툴을 사용하여 vCenter Server 인스턴스에 VASA 공급자를 등록 및 등록 취소할 수 있습니다. 
---
= vCenter Server 인스턴스에 VASA Provider를 등록합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 원격 플러그인 인터페이스용 ONTAP 툴을 사용하여 vCenter Server 인스턴스에 VASA 공급자를 등록 및 등록 취소할 수 있습니다. VASA Provider Settings 섹션에는 선택한 vCenter Server에 대한 VASA Provider 등록 상태가 표시됩니다.

* 단계 *

. 을 사용하여 vSphere Client에 로그인합니다 `\https://vcenterip/ui`
. 바로 가기 페이지에서 플러그인 섹션 아래의 * NetApp ONTAP tools * 를 클릭합니다.
. 설정 * > * VASA 공급자 설정 * 을 선택합니다. VASA 공급자 등록 상태가 등록되지 않음 으로 표시됩니다.
. register * 버튼을 클릭하여 VASA Provider를 등록합니다.
. VASA 공급자 이름을 입력하고 VMware vSphere 애플리케이션 사용자 자격 증명을 위한 ONTAP 툴을 제공한 후 * REGISTER * 를 클릭합니다.
. 등록 및 페이지 새로 고침이 성공하면 UI에 등록된 VASA 공급자의 상태, 이름 및 버전이 표시됩니다. 등록 취소 작업이 활성화됩니다.
. VASA 공급자의 등록을 취소하려면 다음 단계를 수행하십시오.
+
.. VASA Provider를 등록 취소하려면 화면 맨 아래에 있는 * 등록 취소 * 옵션을 선택합니다.
.. VASA 공급자 등록 취소 * 페이지에서 VASA 공급자 이름을 확인할 수 있습니다. 이 페이지에서 응용 프로그램 사용자 자격 증명을 입력하고 * 등록 취소 * 를 클릭합니다.




* 완료 후 *

온보드된 VASA 공급자가 vCenter 클라이언트 UI 및 원격 플러그인 UI의 VASA Provider 아래에 표시되는지 확인합니다.

* 단계 *

. vCenter 클라이언트 UI에서 VASA Provider를 확인하려면 다음 단계를 수행하십시오.
+
.. vCenter Server 로 이동합니다.
.. 관리자 자격 증명으로 로그인합니다.
.. Storage Providers * 를 선택합니다.
.. 구성 * 을 선택합니다.
.. 스토리지 공급자/스토리지 백엔드에서 온보드된 VASA 공급자가 올바르게 나열되는지 확인합니다.


. 원격 플러그인 UI에서 VASA Provider를 확인하려면 다음 단계를 수행하십시오.
+
.. 을 사용하여 vSphere Client에 로그인합니다 `\https://vcenterip/ui`
.. 바로 가기 페이지에서 플러그인 섹션 아래의 * NetApp ONTAP tools * 를 클릭합니다.
.. 등록된 VASA Provider는 개요 페이지와 * Settings * > * VASA Provider Settings * 페이지에서 확인할 수 있습니다.



