---
permalink: release-notes/whats-new-otv-102.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, otv, 10.2, ONTAP tools for VMware vSphere' 
summary: VMware vSphere 10.2용 ONTAP 툴에서 사용할 수 있는 새로운 기능에 대해 알아보십시오. 
---
= VMware vSphere 10.2용 ONTAP 툴의 새로운 기능
:allow-uri-read: 


[role="lead"]
VMware vSphere 10.2용 ONTAP 툴에서 사용할 수 있는 새로운 기능에 대해 알아보십시오.

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../manage/storage-view-datastore.html#ontap-storage-views-for-nfs-datastores[NVMe 프로토콜 지원]
 a| 
VMware vSphere 10.2용 ONTAP 툴은 VMFS 데이터 저장소를 프로비저닝할 때 NVMe/FC 및 NVMe/TCP 프로토콜을 모두 지원합니다. vCenter 인터페이스 내에 원활하게 통합된 워크플로우를 통해 데이터 저장소 프로비저닝이 쉬워집니다. VMFS 데이터 저장소를 프로비저닝할 때 NVMe/FC 및 NVMe/TCP 프로토콜을 사용하여 최적화된 성능, 대규모 확장성 및 여러 데이터 요청의 효율적인 처리, 대폭적인 감소, 효율적인 리소스 관리 등의 이점을 얻을 수 있습니다. NVMe 기반 스토리지 IO는 레거시 데이터 프로토콜에 비해 CPU 활용률이 최대 50% 더 낮습니다.



 a| 
xref:../configure/create-vvols-datastore.html[파이버 채널(FC) 프로토콜 지원]
 a| 
VMware vSphere 10.2용 ONTAP 툴은 VVOL 및 VMFS 데이터 저장소를 프로비저닝하기 위한 FC 프로토콜을 지원합니다. FC 프로토콜 지원의 이점으로는 고성능, 안정성 및 안정성, 확장성, 향상된 보안 및 효율적인 리소스 관리 등이 있습니다.



 a| 
xref:../configure/protect-cluster.html[SnapMirror 활성 동기화]
 a| 
VMware vSphere 10.2용 ONTAP 툴을 통한 SnapMirror Active Sync 지원에는 vCenter UI 내에서 vSphere Metro 스토리지를 구축하기 위한 완벽한 구성 워크플로우를 제공하는 완전히 새로운 보호 클러스터 기능이 포함되어 있습니다. 따라서 전체 사이트 장애 시에도 비즈니스 서비스가 계속 작동하는 확장 클러스터 구성이 가능하여 보조 복사본을 사용하여 애플리케이션을 투명하게 페일오버할 수 있습니다.

[NOTE]
====
SnapMirror 마법사는 SnapMirror Active Sync 외에도 SnapMirror 비동기 및 동기화를 구성할 수 있습니다.

====


 a| 
xref:../protect/enable-storage-replication-adapter.html[SRA(Storage Replication Adapter) 개선 사항]
 a| 
SRA는 VMware SRM(Site Recovery Manager) 사양 기반 DR(재해 복구) 솔루션을 구현합니다. SRM 통합을 통한 SnapMirror 액티브 동기화는 재해 복구 계획 및 조정 솔루션을 지원하여 투명한 애플리케이션 페일오버를 제공합니다.

|===