---
permalink: manage/igroup-management.html 
sidebar: sidebar 
keywords:  
summary: ONTAP에서는 호스트에 대한 볼륨 데이터 경로 액세스를 제공하는 데 엑스포트 정책을 사용하고, igroup을 사용하여 ESXi 호스트에 대한 LUN 데이터 경로 액세스를 제공합니다. 
---
= Igroup 및 엑스포트 정책을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP에서는 엑스포트 정책을 사용하여 호스트에 대한 볼륨 데이터 경로 액세스를 제공하고, 이니시에이터 그룹(igroups)을 사용하여 ESXi 호스트에 대한 LUN(논리 유닛 번호) 데이터 경로 액세스를 제공합니다. VMware vSphere용 ONTAP 툴을 사용하면 igroup을 쉽고 직관적으로 생성하고 풍부한 엔드 투 엔드 워크플로우를 제공할 수 있습니다. 일관성을 보장하기 위해 스토리지 플랫폼에서의 직접 iGroup 생성은 지원되지 않습니다.

vCenter Server의 호스트에 가상 볼륨 데이터 저장소를 생성하거나 마운트하는 경우 데이터 저장소의 프로토콜 유형에 따라 호스트에 볼륨(NFS) 또는 LUN(iSCSI)에 대한 액세스 권한을 부여해야 합니다.

내보내기 정책은 동적이며 새로운 내보내기 정책은 trident-uuid 명명 형식으로 생성됩니다. ONTAP 시스템 관리자에서 * 스토리지 * > * 스토리지 VM * > * [스토리지 VM 이름] * > * 설정 * > * 엑스포트 정책 * 으로 이동하여 엑스포트 정책을 확인하십시오.

VMware vSphere용 ONTAP 툴의 igroup 및 엑스포트 정책은 효율적인 방식으로 관리되며 다음과 같은 이점을 제공합니다.

* 마이그레이션된 엑스포트 정책 및 igroup 지원
* 가상 머신 입력 및 출력 작업을 중단하지 않습니다.
* 수동 개입 없이 추가 호스트에 마운트할 수 있습니다.
* igroup 및 엑스포트 정책의 수를 관리해야 하는 필요성을 최소화합니다.
* 가비지 수집기는 사용되지 않는 관리되는 모든 igroup 및 엑스포트 정책을 주기적으로 자동으로 삭제합니다.
* 호스트 클러스터 수준에서 데이터 저장소가 프로비저닝되면 igroup에 추가되는 호스트 클러스터의 모든 호스트 이니시에이터와 함께 igroup이 생성됩니다.

